### ISSUE TITLE
Support for headers?

### ISSUE THREAD

**Issue by jimthedev** [mauricedb/use-abortable-fetch#1]
Hey there. Would love to use this but at the moment it doesn't look to support headers which would be needed for things like adding tokens to requests. Is that something you can see adding in? I am thinking axios-like functionality.

**Comment by mauricedb** [comment]
@jimthedev Adding support for header should be easy enough. But as there are no tests that would be my first priority to add. These will make life simpler when React upgrades hooks to a real product feature status.

**Comment by mauricedb** [comment]
Hi @jimthedev 	

Just so you know I added support for header using the RequestInit parameter.
