### ISSUE TITLE
Using the hook twice in the same component appears to cause to other fetch to abort

### ISSUE THREAD

**Issue by rshackleton** [mauricedb/use-abortable-fetch#112]
When using the hook twice in the same component I've noticed occasions where one of the fetches is aborted when the other is completed.

Example code:

```
function useProductData(options) {
  const { data: filterData, loading: filterLoading, error: filterError } = useAbortableFetch(
    `/api/products/${options.cultureCode}/filters/${options.filters.categoryId}`,
  );

  const { data: productData, loading: productLoading, error: productError } = useAbortableFetch(
    `/api/products/${options.cultureCode}?${queryString.stringify(options.products)}`,
  );

  return {
    error: filterError || productError,
    filterData,
    loading: filterLoading || productLoading,
    productData,
  };
}
```

When removing one of the calls the other fetch works consistently.

**Comment by mauricedb** [comment]
@rshackleton Not sure what is going on. This should work and I am doing similar things in my own code. Can you create a sample that I can use to investigate?

**Comment by rshackleton** [comment]
I'll see if I can get a codepen put together

**Comment by mauricedb** [comment]
@rshackleton I created a [CodeSandbox samples ](https://codesandbox.io/embed/gallant-bhabha-91f96)based on your code and that seems to work just fine. Please compare this with your code and let me know what is different.

**Comment by rshackleton** [comment]
I think maybe the issue was one of the APIs took a fair bit longer than the other, when I've tested with the APIs completing fairly quickly it didn't fail. Maybe a race condition somewhere?

**Comment by mauricedb** [comment]
@rshackleton Could be the case. However `useAbortableFetch()` should only abort a request when it will be replaced with a newer one and that only happens if the URL or the request options are changed. As long as that isn't the case it should just let the pending fetch request do it's thing.
