### ISSUE TITLE
useLazyAbortableFetch

### ISSUE THREAD

**Issue by AjaxSolutions** [mauricedb/use-abortable-fetch#195]
I'm trying to use useAbortableFetech lazily.  How could I do this?

For comparison, see [useQuery](https://www.apollographql.com/docs/react/api/react-hooks/#usequery) and [useLazyQuery](https://www.apollographql.com/docs/react/api/react-hooks/#uselazyquery) GraphQL hooks.

**Comment by mauricedb** [comment]
Hi @AjaxSolutions,

I am not quite sure what you want to achieve with a lazy query. But if you want to prevent a query from executing when a component first loads you can pass in a null or empty string as URL. In that case nothing will happen.

Something like:
```
const SomeComponent = () => {
  const [url, setUrl] = React.useState(null);
  const { data, loading } = useAbortableFetech(url);

  return (
    <div>
      <pre>{JSON.stringify(data)}</pre>
      <button onClick={() => setUrl("/api/some-data-source")}>Load data</button>
    </div>
  );
};
```

HTH
Maurice

**Comment by AjaxSolutions** [comment]
What would happen if I clicked the 'Load data' button multiple times in a quick succession?  I'd like to abort the previous fetch if it is loading.

**Comment by mauricedb** [comment]
If the url and the optional options object are the same the original request will continue and no new request will start. If one or both is different that the original request will be aborted if it it still in progress and a new request will be started.
