### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by AjaxSolutions** [mauricedb/use-abortable-fetch#196]
I'm not trying to be a smart guy or anything of that sort.  Why the controller is instantiated inside the useEffect as opposed to putting it above the useAbortableFetch line [#5](https://github.com/mauricedb/use-abortable-fetch/blob/master/src/index.ts#L5) so no new instance is created whenever usseEffect has new dependencies?

https://github.com/mauricedb/use-abortable-fetch/blob/master/src/index.ts#L26

**Comment by mauricedb** [comment]
You can only abort a controller instance once, so a new request requires a new controller. The `useEffect()` has a dependency on `[init, url]` so whenever either changes a new one is created and the fetch is started.

**Comment by AjaxSolutions** [comment]
Thx.
