### ISSUE TITLE
How to check if there are no pending requests?

### ISSUE THREAD

**Issue by AjaxSolutions** [mauricedb/use-abortable-fetch#216]
I have multiple independent fetch requests initiated by useAbortableFech.
How can I know when the last request is done, i.e. there are no pending requests?

**Comment by mauricedb** [comment]
When all the `loading` states are false and they all have either a `data` or an `error` returned.

Something like:
```js
const { data: dataOne, loading: loadingOne, error: errorOne } = useAbortableFetch(urlOne);
const { data: dataTwo, loading: loadingTwo, error: errorTwo } = useAbortableFetch(urlTwo);
const allDone = !loadingOne && !loadingTwo && !!dataOne && !!dataTwo
```

**Comment by AjaxSolutions** [comment]
Thanks, but how would I address this issue if the useAbortableFetch calls were in separate files?

**Comment by mauricedb** [comment]
That depends a bit of the structure. But assuming one parent component with two components loading data using `useAbortableFetch()` you could use `setState()` or `useReducer()` in the parent component and pass the `setState()` function to the childeren. 

However if you want to coordinare screen updated between the two using `<Suspense>` might be an easier option. However that is not supproted by `useAbortableFetch()` yet. Been meaning to add `<Suspense>` support but not had time to do so yet.

**Comment by AjaxSolutions** [comment]
I'm posting this just FYI.
I found that https://github.com/tannerlinsley/react-query has an interesting [useIsFetching](https://github.com/tannerlinsley/react-query#useisfetching) hook.

"useIsFetching is an optional hook that returns true if any query in your application is loading or fetching in the background (useful for app-wide loading indicators)."
