### ISSUE TITLE
Consider batching updates to prevent multiple renders

### ISSUE THREAD

**Issue by justinhelmer** [mauricedb/use-abortable-fetch#45]
### Context
Thanks for the very useful hook. We were going to build something similar using `AbortController` and found that you published something that suits our needs.

I have one request that I wanted to bounce off you to optimize the number of times the component lifecycle runs. React currently only batches state updates together inside event handlers (i.e. side-effects). When there are `setState` calls *outside* of event handlers (e.g. after an async fetch), the updates will not be batched. This results in multiple unnecessary renders.

In the case of `use-abortable-fetch`, the result is four renders, which could be reduced to two renders if the state updates were batched.

### Example
Consider the following case:

```js
const { data, loading, error } = useAbortableFetch('/api/some-endpoint');
console.log('data', data);
console.log('loading', loading);
console.log('error', error);
console.log('--------------------------');
```

This will result in the below output:

```
data null
loading false
error null
--------------------------
data null
loading true
error null
--------------------------
data {…}
loading true
error null
--------------------------
data {…}
loading false
error null
--------------------------
```

As you can see, a single fetch is represented by **four unique states**, that results in four renders:
1. [the initial non-loading null state](https://github.com/mauricedb/use-abortable-fetch/blob/master/src/index.ts#L45-L50)
2. [the loading state](https://github.com/mauricedb/use-abortable-fetch/blob/master/src/index.ts#L28-L33)
3. [the loading + data state](https://github.com/mauricedb/use-abortable-fetch/blob/master/src/fetchData.ts#L26-L28)
4. [the non-loading + data state](https://github.com/mauricedb/use-abortable-fetch/blob/master/src/fetchData.ts#L38-L40)

### Potential solutions

Either of the below options would require some bit of refactoring, but would result in the optimal number of renders, and the ideal output for the above example:

```
data null
loading true
error null
--------------------------
data {…}           <--- or data will be null if error is set
loading false
error null
--------------------------
```

#### Option 1 [recommended] - refactor to minimize the number of calls to setState
Instead of updating the state 3x, only update it 1x (when the fetch completes / fails).

If you return the default state with `loading=true` (instead of setting it in `useEffect`), then you can combine renders [1](https://github.com/mauricedb/use-abortable-fetch/blob/master/src/index.ts#L45-L50) & [2](https://github.com/mauricedb/use-abortable-fetch/blob/master/src/index.ts#L28-L33). Then, if you update the `data={}` & `loading=false` states at once, then you can combine renders [3](https://github.com/mauricedb/use-abortable-fetch/blob/master/src/fetchData.ts#L26-L28) and [4](https://github.com/mauricedb/use-abortable-fetch/blob/master/src/fetchData.ts#L38-L40).
> Renders `3` and `4` are already combined in the `error` case

#### Option 2 - unstable_batchedUpdates
There exists a temporary API to force batching. If you wrap the `setState` calls in `ReactDOM.unstable_batchedUpdates`, then multiple calls will be batched.

This option still requires some refactoring, because all of the `setState` calls would need to be in the same `batchedUpdates(() => {})` callback for it to function correctly.

The react team expects to remove this API in the future and instead batch everything by default.

**More info**
@see https://github.com/facebook/react/issues/14259

**Comment by mauricedb** [comment]
Hi @justinhelmer 

4 renders definitely is definitely more that there should be.

Combining the last two `setState()` calls should definitely be done here 👍.

However I am not sure about combining the first two. The initial `loading` state is false and not set to true until loading actually starts in the effect. After this is finished and loading is set to false the URL, or `RequestInit`, could change and a second request could start. If we set the `loading` status to true in the initial state that would not work for subsequent requests. BTW behind the scenes it's actually a counter because of the order of events with multiple requests and cancellation.

I typically use a structure like:
```
const { data, loading, error } = useAbortableFetch(url);

if (error) {
    return <AjaxError error={error} />
}

if (loading || !data) {
    return <Loading />;
}
```

Where the Loading component will be rendered twice, or apparently three times at the moment, but that should not really hurt because that is a simple component.

**Comment by justinhelmer** [comment]
@mauricedb - Thanks for the thoughtful response.

Your solution to prevent multiple unnecessary renders is elegant (ignoring the change you mentioned). However in our case, we are using context providers and letting lower-level components choose what to do in the loading case based on the existence of data. Something like:

```js
const [formattedData, setFormattedData] = useState();

// not showing error case here for the sake of brevity
const { data } = useAbortableFetch(url);
const prevData = usePrevious(data);

useEffect(() => {
  // prevData check necessary to prevent infinite loop from setFormattedData
  if (data && prevData !== data) {
    setFormattedData(format(data));
  }
});

const store = useMemo(() => ({ formattedData }), [formattedData]);
<MyContext.Provider value={store}>{children}</MyContext.Provider>
```

Of course, we are pretty protected from any expensive operations due to multiple renders here, but I am glossing over some other complexities in the context provider that could be avoided if the first two `setState` calls in `useAbortableFetch` were somehow combined.

----

With respect to combining the first two calls, I agree it's not as simple as I had originally thought, due to the consideration of what would happen on subsequent requests. I got a solution that is working given this predicament, but it's not very elegant. I am also not clear of what the implications would be if multiple abortable fetches are used at once. Just for the sake of completeness, I will post it here:

```ts
const useAbortableFetch = <T>(url: string | null, init?: RequestInit): AbortableFetchResult<T> => {
  const [state, setState] = useState<FetchState<T>>({
    data: null,
    loading: 1,
    error: null,
    controller: null
  });

  // store the previous version of the data to check if it has changed
  const prevData = usePrevious(state.data);
const data = state.data !== prevData ? state.data : null;
  const isMounted = useRef(false);
  useLayoutEffect(() => {
    isMounted.current = true;
    return () => {
      isMounted.current = false;
    };
  }, []);

  useLayoutEffect(() => {
    const controller = new AbortController();
    if (url) {
      if (data) {
        setState((oldState: FetchState<T>) => ({
          data: null,
          loading: oldState.loading + 1,
          error: null,
          controller
        }));
      }

      fetchData<T>(prevData, url, init, controller.signal, s => {
        if (isMounted.current) {
          setState(s);
        }
      });
    }

    return () => controller.abort();
  }, [init, url]);

  return {
    data,
    loading: data ? !!state.loading : true,
    error: state.error,
    abort: () => state.controller && state.controller.abort()
  };
};

export default useAbortableFetch;
```

**Comment by justinhelmer** [comment]
I'll post the code here so you can see it and I can reference it later (and move on). I'm fairly sure it's a bad idea, so take it with a grain of salt - but am posting it for completeness.

*index.ts*
```
const useAbortableFetch = <T>(url: string | null, init?: RequestInit): AbortableFetchResult<T> => {
  const [state, setState] = useState<FetchState<T>>({
    data: null,
    loading: 1,
    error: null,
    controller: null
  });

  // only consider data if it has changed from a previous render
  const prevData = usePrevious(state.data);
  const changedData = state.data !== prevData ? state.data : null;

  const isMounted = useRef(false);
  useLayoutEffect(() => {
    isMounted.current = true;
    return () => {
      isMounted.current = false;
    };
  }, []);

  useEffect(() => {
    const controller = new AbortController();
    if (url) {
      // only set loading state if data has changed from a previous render (i.e. subsequent requests)
      if (changedData) {
        setState((oldState: FetchState<T>) => ({
          data: null,
          loading: oldState.loading + 1,
          error: null, // setting this conditionally is probably bad
          controller // setting this conditionally is probably bad
        }));
      }

      // prevData is getting passed to fetchData, so that it can update the loading state correctly
      fetchData<T>(prevData, url, init, controller.signal, s => {
        if (isMounted.current) {
          setState(s);
        }
      });
    }

    return () => controller.abort();
  }, [init, url]);

  return {
    // defaults to null if nothing has changed from a previous render
    data: changedData,

    // default loading state to true unless data has changed from a previous render,
    // in which case use the loading state
    loading: changedData ? !!state.loading : true,

    // probably some bugs/considerations that have not been made w.r.t. error and abort
    error: state.error,
    abort: () => state.controller && state.controller.abort()
  };
};

export default useAbortableFetch;
```

**fetchData.ts**
```
const fetchData = async <T>(
  prevData: T | string | undefined,
  url: string,
  init: RequestInit = {},
  signal: AbortSignal,
  setState: Dispatch<SetStateAction<FetchState<T>>>
): Promise<void> => {
  const actualInit: RequestInit = { ...init, signal };

  try {
    const rsp = await cachedFetch(url, actualInit);
    const contentTypeHeader = rsp.headers.get('content-type');
    let data: T | string | null = null;

    if (contentTypeHeader) {
      if (isJSON(contentTypeHeader)) {
        data = await rsp.json();
      } else {
        data = await rsp.text();
      }
    }

    if (!rsp.ok) {
      const err: any = new Error(rsp.statusText);
      err.status = rsp.status;
      throw err;
    }

    // combining setState calls (3 & 4 from original issue description)
    // ** this is probably the only change that should actually be made
    setState((oldState: FetchState<T>) => {
      // if there was data on a previous render, loading state was never updated (it was derived).
      // therefore, only calculate the loading state in the case where there was not data previously.
      // this does not consider what happens with multiple abortable fetches and is probably bad.
      const loading = !prevData ? oldState.loading - 1 : 0;
      return {
        ...oldState,
        data,
        loading
      };
    });
  } catch (e) {
    const err: Error = e;

    const error = err.name !== 'AbortError' ? err : null;

    setState((oldState: FetchState<T>) => ({
      ...oldState,
      error,
      loading: oldState.loading - 1
    }));
  }
};

export default fetchData;
```
