### ISSUE TITLE
Any way to make the TypeScript definition for `data` a little smarter?

### ISSUE THREAD

**Issue by justinhelmer** [mauricedb/use-abortable-fetch#46]
We noticed you can supply a type, which then becomes used for `data`:
```ts
const { data } = useAbortableFetch<Foo>('/api/some-endpoint');
```
The combined type definition for what gets returned looks like:
```ts
interface AbortableFetchResult<T> = {
  data: T | string | null;
  error: Error | null;
  abort: () => void;
  loading: boolean;
};
```
It's a nice convenience; However, the issue with this is that it forces consumers to allow their typedefs to include string, or otherwise cast `data`:
```ts
if (data) {
  const somethingThatCanOnlyBeFoo: Foo = data; 
  // Error TS2322: Type 'string | Foo' is not assignable to `somethingThatCanOnlyBeFoo`
}
```
```ts
if (data) {
  const somethingThatCanOnlyBeFoo: Foo | string = data; 
  // Works here, but breaks later in places where 'string' is not allowed
}
```
```ts
if (data) {
  const somethingThatCanOnlyBeFoo: Foo = data as Foo; 
  // Works, but defeats any value of passing type to `useAbortableFetch`
}
```

I understand why `string` is an option (i.e. for the case of `res.text()`) - but it breaks for any consumers whose type definitions do NOT want to allow string.

I am not sure that there is a solution for this, because you want to support `res.text()` and TypeScript cannot assume that `T` includes the `string` type if it is needed:
```ts
let data: T | string | null = null; // MUST include string or TS will yell at rsp.text()

if (isJSON(contentTypeHeader)) {
  data = await rsp.json();
} else {
  data = await rsp.text();
}
```
But I wanted to bounce this by you to see if maybe you had an idea that I couldn't figure out that would serve the purpose.

Thanks!

**Comment by mauricedb** [comment]
Hi @justinhelmer,

Sorry for the delay but been on the road for a conference.

I realize that testing for the content type and using rsp.text() if the response isn't JSON introduced this and I don't have a perfect solution.

You solve do this by adding a check for data not being a string

```typescript
type Foo = {
    x:number
}

const { data } = useAbortableFetch<Foo>('/api/some-endpoint');

if (data && typeof data !== 'string') {
    const somethingThatCanOnlyBeFoo: Foo = data; 
} 
```

Or slightly better using a type guard:

```typescript
function isFoo(data: any): data is Foo {
    if (data && data.x && typeof data.x === 'number') {
        return true;
    }

    return false;
}

if (isFoo(data)) {
    const somethingThatCanOnlyBeFoo: Foo = data; 
} 
```

HTH
Maurice

**Comment by justinhelmer** [comment]
@mauricedb - I'm digging the type guard solution.

Thanks for the reply. I would say 2 days is not much of a delay :-)

Hope you enjoyed the conference; cheers.
